### ISSUE TITLE
Cannot install apk after signing: `INSTALL_FAILED_INVALID_APK: failed to extract native libraries, res=-2`

### ISSUE THREAD

**Issue by notyalcs** [imgdrive/signapk#2]
My goal is to be able to open my apk and modify an asset and resign it. I attempted this with signapk.exe and was unable to install the apk after resigning.

I made a new test by just creating a new project in Android Studio (Native C++) and tried Generate Signed Bundle/APK. This apk works no problem and I am able to resign it with Android's apksigner tool.

When I try and use signapk.exe however I run into this error when trying to install the apk:
```
Error code: 'INSTALL_FAILED_INVALID_APK', message='INSTALL_FAILED_INVALID_APK: INSTALL_FAILED_INVALID_APK: Failed to extract native libraries, res=-2'
```

Please let me know if more information from me is needed or if I am doing something wrong.

Thanks

**Comment by imgdrive** [comment]
Please try this build: https://download.yubsoft.com/x64/signapk.exe

For .so files,  if uncompressed, force to align on 4096 boundary.

Reference:
https://stackoverflow.com/questions/63204032/the-apk-rebuild-by-apktool-can-not-be-installed-even-after-zipalign-and-sign

**Comment by notyalcs** [comment]
The build you linked appears to be working for me. Over the next few days I will continue to test it out. For now I am closing this issue. Thank you for all your quick responses and help.

Cheers
